import type { Metadata } from "next";
import Sidebar from "@/components/Sidebar/Sidebar";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigationSections = [
  {
    title: "Pages",
    items: [
      { label: "Dashboard", href: "/pages/dashboard" },
      { label: "Forms", href: "/pages/forms" },
      { label: "Small Market", href: "/pages/small-market" },
      { label: "Tally Large Market", href: "/pages/tally-large-market" },
    ],
  },
  {
    title: "Foundation",
    items: [
      { label: "Colours", href: "/foundation/colour" },
      { label: "Icons", href: "/foundation/icons" },
      { label: "Layout", href: "/foundation/layout" },
      { label: "Layout Grid", href: "/foundation/layout-grid" },
      { label: "Logo", href: "/foundation/logo" },
      { label: "Typography", href: "/foundation/typography" },
    ],
  },
  {
    title: "Components",
    items: [
      { label: "Accordion", href: "/components/accordion" },
      { label: "Alert", href: "/components/alert" },
      { label: "Alert Dialog", href: "/components/alert-dialog" },
      { label: "Aspect Ratio", href: "/components/aspect-ratio" },
      { label: "Avatar", href: "/components/avatar" },
      { label: "Badge", href: "/components/badge" },
      { label: "Breadcrumb", href: "/components/breadcrumb" },
      { label: "Button", href: "/components/button" },
      { label: "Button Group", href: "/components/button-group" },
      { label: "Card", href: "/components/card" },
      { label: "Charts", href: "/components/charts" },
      { label: "Checkbox", href: "/components/checkbox" },
      { label: "Collapsible", href: "/components/collapsible" },
      { label: "Dialog", href: "/components/dialog" },
      { label: "Dropdown Menu", href: "/components/dropdown-menu" },
      { label: "Electricity Usage Widget", href: "/components/electricity-usage-widget" },
      { label: "Input", href: "/components/input" },
      { label: "Popover", href: "/components/popover" },
      { label: "Progress", href: "/components/progress" },
      { label: "Radio Group", href: "/components/radio-group" },
      { label: "Select", href: "/components/select" },
      { label: "Sheet", href: "/components/sheet" },
      { label: "Skeleton", href: "/components/skeleton" },
      { label: "Slider", href: "/components/slider" },
      { label: "Switch", href: "/components/switch" },
      { label: "Table", href: "/components/table" },
      { label: "Tabs", href: "/components/tabs" },
      { label: "Textarea", href: "/components/textarea" },
      { label: "Toast", href: "/components/toast" },
      { label: "Toggle", href: "/components/toggle" },
      { label: "Toggle Group", href: "/components/toggle-group" },
      { label: "Tooltip", href: "/components/tooltip" },
    ],
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Geist+Mono:wght@100..900&family=Inter:wght@100..900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <div className="flex">
          <Sidebar sections={navigationSections} />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
